import { z } from "zod";
import type { LayoutProposal, Scenario, Tile } from "./types";
export const proposalSchema=z.object({layoutTitle:z.string().min(1).max(80),summary:z.string().min(1).max(180),rationale:z.string().min(1).max(500),focusOrder:z.array(z.string()).max(4),decisionPrompts:z.array(z.string()).max(3),tiles:z.array(z.object({id:z.string(),x:z.number().min(0).max(1),y:z.number().min(0).max(1),width:z.number().min(.16).max(1),height:z.number().min(.16).max(1),zIndex:z.number().int().min(1).max(20),priority:z.enum(["primary","secondary","context"]),reason:z.string().min(1).max(180)})).min(1).max(4)});
const business:Tile[]=[{id:"revenue",ownerName:"Jordan",applicationLabel:"Revenue Performance",contentType:"dashboard",source:"sample",x:.055,y:.09,width:.43,height:.53,zIndex:3,minimized:false,priority:"primary"},{id:"forecast",ownerName:"Maya",applicationLabel:"Q4 Forecast Model",contentType:"spreadsheet",source:"sample",x:.42,y:.36,width:.47,height:.49,zIndex:4,minimized:false,priority:"primary"},{id:"deck",ownerName:"Amogh",applicationLabel:"Q3 Review Deck",contentType:"presentation",source:"sample",x:.56,y:.06,width:.35,height:.36,zIndex:2,minimized:false,priority:"context"}];
const engineering:Tile[]=[{id:"editor",ownerName:"Amogh",applicationLabel:"Code Editor",contentType:"code",source:"sample",x:.05,y:.08,width:.52,height:.72,zIndex:3,minimized:false,priority:"primary"},{id:"preview",ownerName:"Maya",applicationLabel:"Application Preview",contentType:"preview",source:"sample",x:.59,y:.08,width:.36,height:.4,zIndex:2,minimized:false,priority:"secondary"},{id:"logs",ownerName:"Jordan",applicationLabel:"Service Logs",contentType:"logs",source:"sample",x:.59,y:.52,width:.36,height:.28,zIndex:4,minimized:false,priority:"secondary"}];
export const scenarioTiles=(s:Scenario)=>structuredClone(s==="business"?business:engineering);
export function fallbackProposal(s:Scenario,tiles:Tile[]):LayoutProposal{const g=s==="business"?[[.03,.08,.49,.78],[.54,.08,.43,.56],[.54,.67,.43,.21]]:[[.03,.08,.58,.82],[.63,.08,.34,.48],[.63,.59,.34,.31]];return{layoutTitle:s==="business"?"Revenue variance decision view":"Debugging triage view",summary:s==="business"?"Compare actual revenue with the forecast while preserving strategic context.":"Prioritize source code while keeping output and logs visible.",rationale:s==="business"?"Revenue evidence and forecast assumptions are placed side by side for direct comparison. The review deck stays visible as supporting context.":"The editor is primary for diagnosis; the preview and logs remain visible for rapid validation.",focusOrder:tiles.map(t=>t.id),decisionPrompts:s==="business"?["Which segment drove the variance?","Which Q4 assumption should change?"]:["Where does the callback diverge?","Do the logs confirm the fix?"],tiles:tiles.map((t,i)=>({id:t.id,x:g[i][0],y:g[i][1],width:g[i][2],height:g[i][3],zIndex:5-i,priority:i<2?"primary":"context",reason:i<2?"Directly supports the decision":"Kept visible for context"})),source:"fallback"}}
export function validateProposal(p:LayoutProposal,active:string[]){const x=proposalSchema.safeParse(p);if(!x.success)return false;const ids=x.data.tiles.map(t=>t.id);return new Set(ids).size===ids.length&&!ids.some(id=>!active.includes(id))&&!active.some(id=>!ids.includes(id))&&x.data.tiles.every(t=>t.x+t.width<=1.001&&t.y+t.height<=1.001)}

