"use client";
import { Rnd } from "react-rnd";
import { BarChart3,Code2,FileChartColumn,Focus,Grip,Minus,PanelTop,RotateCcw,Sheet,Terminal } from "lucide-react";
import type { Tile } from "@/lib/types";
import { useWorkspace } from "@/store/workspace";
const Icon=({type}:{type:Tile["contentType"]})=>type==="dashboard"?<BarChart3/>:type==="spreadsheet"?<Sheet/>:type==="presentation"?<FileChartColumn/>:type==="code"?<Code2/>:type==="logs"?<Terminal/>:<PanelTop/>;
function Content({tile}:{tile:Tile}){if(tile.contentType==="dashboard")return <div className="dashboard"><div className="metric"><span>Q3 revenue</span><b>$4.82M</b><small>8.4% below plan</small></div><div className="chart">{[42,58,51,70,64,78,55,73,66,84,62,76].map((h,i)=><i key={i} style={{height:`${h}%`}}/> )}</div><div className="legend"><span>Enterprise +12%</span><span>Mid-market -18%</span><span>Expansion +4%</span></div></div>;
if(tile.contentType==="spreadsheet")return <div className="sheet"><div className="sheet-head"><span>Segment</span><span>Q3 Actual</span><span>Q4 Plan</span><span>Variance</span></div>{[["Enterprise","$2.18M","$2.42M","+11%"],["Mid-market","$1.44M","$1.73M","+20%"],["SMB","$1.20M","$1.27M","+6%"],["Total","$4.82M","$5.42M","+12%"]].map((r,i)=><div className={i===3?"total":""} key={r[0]}>{r.map(c=><span key={c}>{c}</span>)}</div>)}</div>;
if(tile.contentType==="presentation")return <div className="deck"><small>Q3 BUSINESS REVIEW</small><h3>Growth held.<br/>Mix shifted.</h3><p>Enterprise resilience offset by mid-market conversion pressure.</p><div><b>+7%</b><span>YoY growth</span></div></div>;
if(tile.contentType==="code")return <div className="code"><span>18</span><code>const callback = validateRedirect(url);</code><span>19</span><code>if (!callback.allowed) return fallback;</code><span>20</span><code className="accent">return redirect(callback.target);</code><span>21</span><code>{`// compare expected origin`}</code></div>;
if(tile.contentType==="logs")return <div className="logs"><p>12:41:08 auth.callback received</p><p>12:41:08 origin mismatch <b>/signin</b></p><p>12:41:09 fallback applied</p><p className="ok">12:42:11 healthcheck 200</p></div>;
return <div className="preview"><div className="browserbar">mosaic.local/review</div><div className="previewbody"><div className="previewmark">M</div><h3>Welcome back</h3><button>Continue to workspace</button></div></div>}
export function ShareTile({tile,bounds}:{tile:Tile;bounds:{width:number;height:number}}){const update=useWorkspace(s=>s.updateTile),front=useWorkspace(s=>s.bringForward),focus=useWorkspace(s=>s.focus),undo=useWorkspace(s=>s.undo);if(tile.minimized)return <button className="minimized" style={{zIndex:tile.zIndex}} onClick={undo}><Icon type={tile.contentType}/>{tile.applicationLabel}<RotateCcw size={13}/></button>;return <Rnd bounds="parent" minWidth={240} minHeight={150} position={{x:tile.x*bounds.width,y:tile.y*bounds.height}} size={{width:tile.width*bounds.width,height:tile.height*bounds.height}} onMouseDown={()=>front(tile.id)} onDragStop={(_,d)=>update(tile.id,{x:d.x/bounds.width,y:d.y/bounds.height})} onResizeStop={(_,__,ref,___,pos)=>update(tile.id,{x:pos.x/bounds.width,y:pos.y/bounds.height,width:ref.offsetWidth/bounds.width,height:ref.offsetHeight/bounds.height})} style={{zIndex:tile.zIndex,transition:"width .45s,height .45s,transform .45s"}} className="tile"><header><span className={`app-icon ${tile.contentType}`}><Icon type={tile.contentType}/></span><div><b>{tile.applicationLabel}</b><small>{tile.ownerName} · {tile.source==="zoom"?"LIVE":"GUIDED SAMPLE"}</small></div><Grip className="drag" size={16}/><button aria-label="Focus" onClick={()=>focus(tile.id)}><Focus size={15}/></button><button aria-label="Minimize" onClick={()=>update(tile.id,{minimized:true})}><Minus size={15}/></button></header><Content tile={tile}/><span className="live-pill">{tile.source==="zoom"?"LIVE":"SAMPLE"}</span></Rnd>}


